version: "3.8"

services:
  web:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/var/www/html
      - ./_logs:/var/logs
      - ./_ssl:/ssl
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    links:
      - backend
    networks:
      - jas-network

  backend:
    image: node:15.13.0-alpine
    user: "node"
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./backend:/home/node/app
      - ./.env:/home/node/app/src/.env
      - ./_uploads:/var/uploads
    environment:
      - NODE_ENV=production
      - TS_NODE_TRANSPILE_ONLY=TRUE
    command: "npm run docker"
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - jas-network

  mongodb:
    image: mongo:4.2.0
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./_db:/data/db
    environment:
      - MONGO_INITDB_DATABASE=jva
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=jas
    networks:
      - jas-network

networks:
  jas-network:
